### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kbeamnsidc**
Correct typo: providence -> provenance.

### CODE REVIEW

**Comment by kbeamnsidc** [comment]
I'm looking into signing the CLA, but this may take some time as I figure out any institutional considerations.

**Comment by alxmrs** [comment]
Thanks for the typo fix! Let me know how I can help

**Comment by kbeamnsidc** [comment]
If you don't want to wait for my signed CLA, feel free to close my PR and make the change if you prefer. I'll still figure out the CLA since it will probably be useful in the future. Thank you!

**Comment by alxmrs** [comment]
That sounds good to me. Fixed in #22. 

We're happy to have your future changes, too.

**Pull request closed without merging**
